// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGvnozgW6z68yRwUii4OUpulXd6-hwI74',
    appId: '1:234073029931:web:55afd2a3311147296b196e',
    messagingSenderId: '234073029931',
    projectId: 'excoffee-8a23b',
    authDomain: 'excoffee-8a23b.firebaseapp.com',
    storageBucket: 'excoffee-8a23b.firebasestorage.app',
    measurementId: 'G-511SFFC73H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAr7P0Z6cYCosGfSBc-Dd-s_99aWcgxfk',
    appId: '1:234073029931:android:010e95d645873fe76b196e',
    messagingSenderId: '234073029931',
    projectId: 'excoffee-8a23b',
    storageBucket: 'excoffee-8a23b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChhwuv6m7YsUpYkGOQE-5eZG3izi3dXWI',
    appId: '1:234073029931:ios:f2b7acf44a0f893d6b196e',
    messagingSenderId: '234073029931',
    projectId: 'excoffee-8a23b',
    storageBucket: 'excoffee-8a23b.firebasestorage.app',
    iosBundleId: 'com.example.exultAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChhwuv6m7YsUpYkGOQE-5eZG3izi3dXWI',
    appId: '1:234073029931:ios:f2b7acf44a0f893d6b196e',
    messagingSenderId: '234073029931',
    projectId: 'excoffee-8a23b',
    storageBucket: 'excoffee-8a23b.firebasestorage.app',
    iosBundleId: 'com.example.exultAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGvnozgW6z68yRwUii4OUpulXd6-hwI74',
    appId: '1:234073029931:web:93838996fac5c1f26b196e',
    messagingSenderId: '234073029931',
    projectId: 'excoffee-8a23b',
    authDomain: 'excoffee-8a23b.firebaseapp.com',
    storageBucket: 'excoffee-8a23b.firebasestorage.app',
    measurementId: 'G-5STJCKLP2D',
  );
}
